added comments on installation and running
precice/systemtests pull request #11
Opened 2018-10-30 15:52 UTC by BenjaminRueth

Some comments on installation and running of the systemtests.

2018-10-30 19:24 UTC, floli requested changes
Please make sure, it's clear that systemtests are for internal tests and nothing like the official docker image.

Still, thanks for the documentation additions!

2018-10-30 19:24 UTC, floli commented on README.md
> +python3 -c 'import docker; docker.build_image("precice-interactive", "Dockerfile.precice", force_rebuild = False)'
This command uses internal stuff and may break without any notice. Anyway, why do you use it at all? `local_test.py` builds the precice image just fine.

If you want to build your own precice image use the standard docker commands `docker build -t precice/precice:develop -f Dockerfile.precice --build-arg ...`

2018-10-30 19:24 UTC, floli commented on README.md
> +* Run the image in interactive mode via ```docker run -ti precice-interactive /bin/bash```.
Maybe we should provide an official docker image, but the Dockerfile here in the systemtest repo is not intended for general use (albeit it *may* work just fine)

2018-10-31 15:12 UTC, BenjaminRueth commented on README.md
> +* Run the image in interactive mode via ```docker run -ti precice-interactive /bin/bash```.
Should we entirely remove the paragraph "Build & Run preCICE image interactively" in the README.md and provide an official preCICE docker image instead?

2018-11-01 08:47 UTC, floli commented on README.md
> +* If you run into problems during compilation of preCICE in your docker container, use ```force_rebuild=True```.
Rather `--force_rebuild precice` as argument to `local_test.py`

2018-11-13 16:22 UTC, merged